data: !!python/object:utils.HParams
  batch_type: dynamic
  filter_length: 2048
  hop_length: 512
  max_frames_in_batch: 5000
  max_wav_value: 32768.0
  mel_fmax: 22050
  mel_fmin: 0.0
  n_mel_channels: 80
  sampling_rate: 44100
  shuffle_size: 1000
  sort_size: 500
  spk:
    bachongshenzi: 0
  training_files: "ckpts/\u516B\u91CD\u795E\u5B50/train.list"
  unit_interpolate_mode: nearest
  validation_files: "ckpts/\u516B\u91CD\u795E\u5B50/val.list"
  vol_aug: true
  vol_embedding: true
  win_length: 2048
model: !!python/object:utils.HParams
  filter_channels: 768
  flow_share_parameter: false
  gin_channels: 768
  hidden_channels: 192
  inter_channels: 192
  kernel_size: 3
  n_flow_layer: 4
  n_heads: 2
  n_layers: 6
  n_layers_q: 3
  n_layers_trans_flow: 3
  n_speakers: 1
  p_dropout: 0.1
  resblock: '1'
  resblock_dilation_sizes:
  - - 1
    - 3
    - 5
  - - 1
    - 3
    - 5
  - - 1
    - 3
    - 5
  resblock_kernel_sizes:
  - 3
  - 7
  - 11
  speaker_embedding: false
  speech_encoder: vec768l12
  ssl_dim: 768
  upsample_initial_channel: 512
  upsample_kernel_sizes:
  - 16
  - 16
  - 4
  - 4
  - 4
  upsample_rates:
  - 8
  - 8
  - 2
  - 2
  - 2
  use_automatic_f0_prediction: true
  use_depthwise_conv: false
  use_spectral_norm: false
  use_transformer_flow: false
  vocoder_name: nsf-hifigan
  vol_embedding: true
train: !!python/object:utils.HParams
  all_in_mem: false
  betas:
  - 0.8
  - 0.99
  c_kl: 1.0
  c_mel: 45
  epochs: 100
  eps: 1.0e-09
  fp16_run: false
  half_type: fp16
  init_lr_ratio: 1
  keep_ckpts: 3
  learning_rate: 5.0e-05
  log_interval: 50
  lr_decay: 0.999875
  max_speclen: 512
  num_workers: 5
  per_step_epoch: 30000
  pin_memory: true
  port: '6789'
  prefetch: 5
  seed: 1234
  segment_size: 10240
  skip_optimizer: true
  train_env: !!python/object:utils.HParams
    LOCAL_RANK: 0
    MASTER_ADDR: localhost
    MASTER_PORT: 10086
    RANK: 0
    WORLD_SIZE: 1
  train_type: finetune
  use_sr: true
  vol_aug: true
  warmup_epochs: 0
