data:
  block_size: 512
  cnhubertsoft_gate: 10
  duration: 1.5
  encoder: vec768l12
  encoder_hop_size: 320
  encoder_out_channels: 768
  encoder_sample_rate: 16000
  extensions:
  - wav
  sampling_rate: 44100
  shuffle_size: 100
  sort_size: 50
  hop_length: 512
  max_frames_in_batch: 3000
  batch_size: 48
  batch_type: dynamic
  training_files: filelists/train.txt
  unit_interpolate_mode: nearest
  validation_files: filelists/val.txt

infer:
  method: dpm-solver++
  speedup: 10
model:
  k_step_max: 100
  n_chans: 512
  n_hidden: 256
  n_layers: 20
  n_spk: 1
  timesteps: 1000
  type: Diffusion
  use_pitch_aug: true

train:
  fp16_run: false
  seed: 42
  log_interval: 10
  per_epoch_save: 20
  epochs: 100
  decay_step: 100000
  num_workers: 5
  prefetch: 5
  pin_memory: true
  cache_fp16: true
  save_opt: false
  weight_decay: 0
  gamma: 0.5
  lr: 0.0001
  skip_optimizer: false
  train_type: finetune
  per_step_epoch: 30000
  train_env: # 训练环境配置
    MASTER_ADDR: "localhost"
    MASTER_PORT: 10086
    WORLD_SIZE: 1
    LOCAL_RANK: 0
    RANK: 0
    
vocoder:
  ckpt: pretrain/nsf_hifigan/model
  type: nsf-hifigan
